---
- name: Stop vaultwarden container
  docker_container:
    name: vaultwarden
    state: stopped

- name: Migrate vaultwarden data
  copy:
    src: "{{ vaultwarden_data }}"
    dest: /opt/vaultwarden/
    owner: vaultwarden
    group: vaultwarden
    mode: '0700'
  notify: Restart vaultwarden container

