---
- name: Gather infos of running vaultwarden
  docker_container_info:
    name: vaultwarden
  register: result

- name: Current vaultwarden status
  ansible.builtin.debug:
    msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

- name: Remove vaultwarden container
  docker_container:
    name: vaultwarden
    state: absent
  when: result.exists

- name: Backup vaultwarden data
  community.general.archive:
    path: "{{ vaultwarden_install_path }}"
    dest: /opt/vaultwarden-backup.tgz 
    remove: yes

- name: Remove user "vaultwarden"  
  user:
    name: vaultwarden
    state: absent

- name: Remove group "vaultwarden"
  group:
    name: vaultwarden
    state: absent

