- name: Create group "vaultwarden"
  group:
    name: vaultwarden
    state: present
    gid: "{{ vaultwarden_gid }}"
  when: vaultwarden_install is defined and vaultwarden_install == true

- name: Create user "vaultwarden"  
  user:
    name: vaultwarden
    uid: "{{ vaultwarden_uid }}"
    group: vaultwarden
    shell: /sbin/nologin
    create_home: no
    append: yes
    state: present
  when: vaultwarden_install is defined and vaultwarden_install == true

