- name: Create group "vaultwarden"
  group:
    name: vaultwarden
    state: present
    gid: "{{ vaultwarden_gid | default(9009) }}"
  when: vaultwarden_install is defined and vaultwarden_install == true

- name: Create user "vaultwarden"  
  user:
    name: vaultwarden
    uid: "{{vaultwarden_uid | default(9009)}}"
    group: vaultwarden
    shell: /sbin/nologin
    create_home: no
    append: yes
    state: "{{ 'present' if vaultwarden_install == true else 'absent' }}"
