---
- name: Spawn vaultwarden container
  docker_container:
    name: "{{ vaultwarden_container_name }}"
    image: "vaultwarden/server:{{ vaultwarden_image_tag }}"
    pull: "{{ vaultwarden_pull }}"
    user: "{{ vaultwarden_uid }}"
    networks: "{{ vaultwarden_networks | default(omit) }}"
    volumes:
      - "{{ vaultwarden_install_path }}:/data"
    env:
      VIRTUAL_HOST: "{{ vaultwarden_domain | default(omit) }}"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "{{ vaultwarden_domain | default(omit) }}"
      ADMIN_TOKEN: "{{ vaultwarden_admin_token | default(omit) }}"
      SIGNUPS_ALLOWED: "{{ vaultwarden_signup | string }}"
      INVITATIONS_ALLOWED: "{{ vaultwarden_invitations_allowed | string }}"
      SHOW_PASSWORD_HINT: "{{ vaultwarden_password_hint | string }}"
      DISABLE_ADMIN_TOKEN: "{{ vaultwarden_disable_admin_token | string}}"
      SMTP_HOST: "{{ vaultwarden_smtp_host | default(omit) }}"
      SMTP_FROM: "{{ vaultwarden_smtp_from | default(omit) }}"
      SMTP_PORT: "{{ vaultwarden_smtp_port | default(omit) }}"
      SMTP_SSL: "{{ vaultwarden_smtp_ssl | default(omit) }}"
      SMTP_EXPLICIT_TLS: "{{ vaultwarden_smtp_explicit_tls | default(omit) }}"
      SMTP_USERNAME: "{{ vaultwarden_smtp_username | default(omit) }}"
      SMTP_PASSWORD: "{{ vaultwarden_smtp_password | default(omit) }}"
      SMTP_AUTH_MECHANISM: "{{ vaultwarden_smtp_authmech | default(omit) }}"
    restart_policy: "{{ vaultwarden_restart_policy }}"
    state: "{{ vaultwarden_container_state }}"
