---
- name: Push env file
  template:
    src: "{{ role_path }}/templates/vaultwarden.env.j2"
      #  src: "{{ role_path }}/templates/{{ 'vaultwarden.env.j2' if vaultwarden_smtp_host is undefined else 'vaultwarden.smtp.env.j2' }}"
    dest: "{{ vaultwarden_remote_env_path }}" 
  register: envpush

- name: Spawn vaultwarden container
  docker_container:
    name: "{{ vaultwarden_container_name }}"
    image: "vaultwarden/server:{{ vaultwarden_image_tag|string }}"
    pull: "{{ vaultwarden_pull }}"
    user: "{{ vaultwarden_uid }}"
    networks: "{{ vaultwarden_networks }}"
    ports: "{{ vaultwarden_ports }}"
    volumes:
      - "{{ vaultwarden_install_path|string }}:/data"
    env_file: "{{ vaultwarden_remote_env_path }}"
    labels: "{{ vaultwarden_labels }}"
    restart_policy: "{{ vaultwarden_restart_policy }}"
    recreate: "{{ 'yes' if envpush.changed else 'no' }}"
    state: "{{ vaultwarden_container_state }}"
