- name: Start vaultwarden container
  docker_container:
    name: vaultwarden
    image: "vaultwarden/server:{{ vaultwarden_image_tag | default('latest') }}"
    pull: "{{ vaultwarden_pull | default('yes') }}"
    user: "{{ vaultwarden_uid | default(9009) }}"
    networks:
      - name: "{{ vaultwarden_nginx_network | default('nginx_network') }}"
    volumes:
      - /opt/vaultwarden:/data
    env:
      VIRTUAL_HOST: "{{ vaultwarden_domain | default(omit) }}"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "{{ vaultwarden_domain | default(omit) }}"
      ADMIN_TOKEN: "{{ vaultwarden_admin_token }}"
      SIGNUPS_ALLOWED: "{{ vaultwarden_signup | default('false')}}"
      SHOW_PASSWORD_HINT: "{{ vaultwarden_password_hint | default('false') }}"
      SMTP_HOST: "{{ vaultwarden_smtp_host | default(omit) }}"
      SMTP_FROM: "{{ vaultwarden_smtp_from | default(omit) }}"
      SMTP_PORT: "{{ vaultwarden_smtp_port | default(omit) }}"
      SMTP_SSL: "{{ vaultwarden_smtp_ssl | default(omit) }}"
      SMTP_EXPLICIT_TLS: "{{ vaultwarden_smtp_explicit_tls | default(omit) }}"
      SMTP_USERNAME: "{{ vaultwarden_smtp_username | default(omit) }}"
      SMTP_PASSWORD: "{{ vaultwarden_smtp_password | default(omit) }}"
      SMTP_AUTH_MECHANISM: "{{ vaultwarden_smtp_authmech | default(omit) }}"
    restart_policy: always
    state: "{{ 'started' if vaultwarden_install == true else 'absent' }}"
