- name: Start vaultwarden container
  docker_container:
    name: vaultwarden
    image: vaultwarden/server:{{ vaultwarden_image_tag | default(latest) }}
    user: "{{ vaultwarden_uid | default(9009) }}"
    networks:
      - name: "{{ vaultwarden_nginx_network | default('nginx_network') }}"
    volumes:
      - /opt/vaultwarden:/data
    env: "{{ vaultwarden_env }}"
    restart_policy: always
    state: "{{ 'started' if vaultwarden_install == true else 'absent' }}"
