- name: Create vaultwarden data volume
  file:
    path: "{{ vaultwarden_install_path }}"
    state: directory
    owner: vaultwarden
    group: vaultwarden
    mode: '0700'
  when: vaultwarden_install is defined and vaultwarden_install == true
