---
- name: Start vaultwarden container
  docker_container:
    name: vaultwarden
    state: started

- name: Stop vaultwarden container
  docker_container:
    name: vaultwarden
    state: stopped

- name: Restart vaultwarden container
  docker_container:
    name: vaultwarden
    state: started
    restart: yes

