# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: 'jchroback.vaultwarden'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: 'jchroback.vaultwarden'

      - name: setup python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install dependencies
        run: pip3 install yamllint

      - name: lint
        run: |
          yamllint .

  release:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.0
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
